spring.application.name=opensearch
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=SYSTEM
spring.datasource.password=Oracle-free-2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

opensearch.uris=http://localhost:9200
opensearch.username=admin
opensearch.password=Opensearch-node-2025
opensearch.connection-timeout-millis=1000
opensearch.socket-timeout-millis=3000

#spring.data.elasticsearch.uris=http://localhost:9200
#spring.data.elasticsearch.username=admin
#spring.data.elasticsearch.password=Opensearch-node-2025
#spring.data.elasticsearch.connection-timeout=1000
#spring.data.elasticsearch.read-timeout=3000
#
#spring.elasticsearch.rest.username=admin
#spring.elasticsearch.rest.password=Opensearch-node-2025
#spring.elasticsearch.rest.uris=http://localhost:9200

# B?t batch insert cho JPA
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true # Quan tr?ng cho c�c entity c� @Version


logging.level.org.springframework.data.elasticsearch: INFO
logging.level.org.elasticsearch.client: INFO
